### ISSUE TITLE
Ctrl-Shift-S to submit fails

### ISSUE THREAD

**Issue by Hong-Revo** [MikhailArkhipov/vscode-r#13]
![image](https://user-images.githubusercontent.com/11328890/49567362-90c92980-f981-11e8-9a9e-ab8603b2538e.png)

Here is the log:
```
  ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asHoverContent (C:\Users\hongooi\.vscode\extensions\mikhail-arkhipov.r-0.0.3\node_modules\vscode-languageclient\lib\protocolConverter.js:101:27)
	at asHover (C:\Users\hongooi\.vscode\extensions\mikhail-arkhipov.r-0.0.3\node_modules\vscode-languageclient\lib\protocolConverter.js:134:31)
	at <anonymous>
```

**Comment by MikhailArkhipov** [comment]
Yes, there was duplicate command with 'source file'.

**Comment by MikhailArkhipov** [comment]
0.0.4
