### ISSUE TITLE
Occasional null ref at startup

### ISSUE THREAD

**Issue by MikhailArkhipov** [MikhailArkhipov/vscode-r#5]
Mojave - looks like idle may be happening before server is fully initialized

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.R.LanguageServer.Services.IdleTimeService.HandleIdle() in C:\vscode-r\src\LanguageServer\Impl\Services\Idle\IdleTimeService.cs:line 35
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
[Info  - 3:56:30 PM] Connection to server got closed. Server will restart.
[Info  - 3:56:32 PM] Available R interpreters:
[Info  - 3:56:32 PM] 	[0] R 3.4
```

**Comment by MikhailArkhipov** [comment]
https://github.com/MikhailArkhipov/vscode-r/releases/tag/0.0.2
