### ISSUE TITLE
Support for dotnet 5 (current)

### ISSUE THREAD

**Issue by adroste** [MikhailArkhipov/vscode-r#52]
Request:

Support for .NET 5.0. 3.1 LTS won't last forever.

**Comment by MikhailArkhipov** [comment]
Try https://github.com/MikhailArkhipov/vscode-r/releases/tag/0.0.16 you can install it from VSIX. Are you on Windows, Mac or Linux?

**Comment by adroste** [comment]
![Screenshot 2021-02-06 at 16 35 31](https://user-images.githubusercontent.com/18649298/107122684-7492e100-6899-11eb-80d8-b3d0c619b922.png)

I'm on macOS. Does not seem to work on 5.0.
Preference Pane is visible -> Help pages work. No IntelliSense help displayed.

**Comment by MikhailArkhipov** [comment]
I assume you do have .NET 5.0 runtime on Mac? The .NET check can be bypassed via `"r.dependencyChecks": false`. 

Sorry I have retired from Microsoft and don't have modern Macs anymore. I own couple of old ones, but they don't run modern MacOS :-). So meanwhile I am trying to locate suitable machine... wish Apple had Macbook Pro on M1...

**Comment by adroste** [comment]
```bash
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.1
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/Cellar/dotnet/5.0.102/libexec/sdk/5.0.102/

Host (useful for support):
  Version: 5.0.2
  Commit:  de79212ef1

.NET SDKs installed:
  5.0.102 [/usr/local/Cellar/dotnet/5.0.102/libexec/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.2 [/usr/local/Cellar/dotnet/5.0.102/libexec/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/local/Cellar/dotnet/5.0.102/libexec/shared/Microsoft.NETCore.App]
```

With dependency checks disabled, plugin loads but the next error appears:
![Screenshot 2021-02-06 at 19 53 25](https://user-images.githubusercontent.com/18649298/107128114-6a81da00-68bb-11eb-9a30-d61a60cf83e5.png)
with the corresponding log:

```
[2021-02-06 19:51:49.215] [exthost] [error] [Mikhail-Arkhipov.r] provider FAILED
[2021-02-06 19:51:49.215] [exthost] [error] Error: name must not be falsy
	at Function.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:80:32893)
	at new o (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:80:32842)
	at new o (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:80:19977)
	at asSymbolInformation (/Users/alexander/.vscode/extensions/mikhail-arkhipov.r-0.0.16/node_modules/vscode-languageclient/lib/protocolConverter.js:449:22)
	at /Users/alexander/.vscode/extensions/mikhail-arkhipov.r-0.0.16/node_modules/vscode-languageclient/lib/protocolConverter.js:429:42
	at Array.map (<anonymous>)
	at Object.asSymbolInformations (/Users/alexander/.vscode/extensions/mikhail-arkhipov.r-0.0.16/node_modules/vscode-languageclient/lib/protocolConverter.js:429:23)
	at /Users/alexander/.vscode/extensions/mikhail-arkhipov.r-0.0.16/node_modules/vscode-languageclient/lib/client.js:1088:70
```


--- 

Further tests:
I downgraded to .NET Core 3.1 LTS and v0.0.15 of your extension.
The error does seem to be related to the .NET 5 update. (Sorry for that)
=> Same error as above:

```
[2021-02-06 19:48:43.381] [exthost] [error] [Mikhail-Arkhipov.r] provider FAILED
[2021-02-06 19:48:43.382] [exthost] [error] Error: name must not be falsy
	at Function.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:80:32893)
	at new o (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:80:32842)
	at new o (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:80:19977)
	at asSymbolInformation (/Users/alexander/.vscode/extensions/mikhail-arkhipov.r-0.0.15/node_modules/vscode-languageclient/lib/protocolConverter.js:449:22)
	at /Users/alexander/.vscode/extensions/mikhail-arkhipov.r-0.0.15/node_modules/vscode-languageclient/lib/protocolConverter.js:429:42
	at Array.map (<anonymous>)
	at Object.asSymbolInformations (/Users/alexander/.vscode/extensions/mikhail-arkhipov.r-0.0.15/node_modules/vscode-languageclient/lib/protocolConverter.js:429:23)
	at /Users/alexander/.vscode/extensions/mikhail-arkhipov.r-0.0.15/node_modules/vscode-languageclient/lib/client.js:1088:70
```

A similiar issue could be #48 .
I'm on macOS 11.1, VS Code 1.53.0, R/Radian installed via brew, Interpreter Path set to `/usr/local/Cellar/r/4.0.3/bin/R` and terminal path to `/usr/local/bin/radian`.

What is weird though is, that the `Run line` command works. It starts radian and executes the selected line(s).

**Comment by MikhailArkhipov** [comment]
Updated VSIX. Here is my MB Air M1 with 5.0 and Rosetta. Please try it out.
https://github.com/MikhailArkhipov/vscode-r/releases/tag/0.0.16

![image](https://user-images.githubusercontent.com/12820357/107841866-d65cba80-6d73-11eb-97a0-27180f8e8c78.png)

**Comment by MikhailArkhipov** [comment]
Closing per 0.0.17.
