### ISSUE TITLE
Can't bring up R console in 0.02

### ISSUE THREAD

**Issue by Hong-Revo** [MikhailArkhipov/vscode-r#7]
Apologies in advance for the really dumb question. I just updated to version 0.02, and I can't seem to find how to get the R console up. Pressing Ctrl-Shift-` just opens the default Powershell console.

**Comment by Hong-Revo** [comment]
I just went to View->Command Palette-> R: Open R Terminal, and it threw an error: `command 'r.openTerminal' not found`. That doesn't look good.... 

![image](https://user-images.githubusercontent.com/11328890/48990535-f6980300-f182-11e8-8161-f7de7fbae264.png)

**Comment by Hong-Revo** [comment]
You mean this?

```
  INFO no standard startup: not the explorer viewlet
workbench.main.js:sourcemap:294 [Extension Host] Activating extension 'Mikhail-Arkhipov.r' failed: spawn /usr/bin/ruby ENOENT.
t.log @ workbench.main.js:sourcemap:294
workbench.main.js:sourcemap:294 [Extension Host] Activating extension `Mikhail-Arkhipov.r` failed:  spawn /usr/bin/ruby ENOENT
t.log @ workbench.main.js:sourcemap:294
workbench.main.js:sourcemap:294 [Extension Host] Here is the error stack:  Error: spawn /usr/bin/ruby ENOENT
	at _errnoException (util.js:1024:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
	at onErrorNT (internal/child_process.js:372:16)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)
workbench.main.js:sourcemap:3306 Activating extension 'Mikhail-Arkhipov.r' failed: spawn /usr/bin/ruby ENOENT.
g._logMessageInConsole @ workbench.main.js:sourcemap:3306
workbench.main.js:sourcemap:2429 Error: command 'r.openTerminal' not found
    at t._tryExecuteCommand (workbench.main.js:sourcemap:3041)
    at workbench.main.js:sourcemap:3041
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188)
t.onDidNotificationChange @ workbench.main.js:sourcemap:2429
```

**Comment by MikhailArkhipov** [comment]
Yes, there was incorrect check for Mac which caused Mac-specific code to be executed on other platforms.

**Comment by HLFH** [comment]
Thanks for the commit. Can you please release a new version so I can run it on Windows?

**Comment by MikhailArkhipov** [comment]
0.0.3 doesn't run on Windows?

**Comment by Hong-Revo** [comment]
I was going to say that 0.0.3 doesn't show up, but I just opened up VSCode and the update has been installed. It works now!

**Comment by HLFH** [comment]
Same issue on 0.0.3

**Comment by Hong-Revo** [comment]
I just got this error again, but I can't reproduce it.

**Comment by Hong-Revo** [comment]
It seems to happen only on opening a folder for the 1st time. Here's the log:

```
INFO no standard startup: not just one text editor
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2429 Error: command 'r.openTerminal' not found
    at t._tryExecuteCommand (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3041:597)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3041:458
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by Hong-Revo** [comment]
I just realised I was getting this error when the folder (=project?) is for an R package containing C++ code. I installed the C++ extension, and the error went away. No idea if there is any real relationship though.

**Comment by Hong-Revo** [comment]
Another error, this time when I opened a folder but didn't have a file open in the editor window:

```
Error: command 'r.openTerminal' not found
    at t._tryExecuteCommand (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3041:597)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3041:458
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
t.onDidNotificationChange @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2429
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1446
ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asHoverContent (C:\Users\hongooi\.vscode\extensions\mikhail-arkhipov.r-0.0.5\node_modules\vscode-languageclient\lib\protocolConverter.js:101:27)
	at asHover (C:\Users\hongooi\.vscode\extensions\mikhail-arkhipov.r-0.0.5\node_modules\vscode-languageclient\lib\protocolConverter.js:134:31)
	at <anonymous>
```

**Comment by Hong-Revo** [comment]
If I wait a few seconds to open the terminal, rather than immediately after opening the folder, the problem goes away. Guess the code just needs some time to load.
